### ISSUE TITLE
Bunnyfap media share

### ISSUE THREAD

**Issue by PerilousGambit** [bunnyfap/bf-client#87]
I want to be able to get an URI so I can share to others a hot-linkable media in BunnyFap they can click on and like/fav or tag. So not just the media, but also the interface (source and media uri are not useful).

**Comment by ffactory-ofcl** [comment]
Seems as though this was already implemented.

**Comment by PerilousGambit** [comment]
Implemented in e93bf126586282d4a71787613a9c32a45eb01cb8
